version: '3.8'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: chatgpt-surrealdb
    ports:
      - "8001:8000"
    command: start --log trace --user root --pass root memory
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  chatgpt-api:
    build: .
    container_name: chatgpt-fastapi
    ports:
      - "8000:8000"
    environment:
      - SURREALDB_URL=ws://surrealdb:8000/rpc
      - SURREALDB_NAMESPACE=chatgpt
      - SURREALDB_DATABASE=conversations
      - SURREALDB_USERNAME=root
      - SURREALDB_PASSWORD=root
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-3.5-turbo
      - DEBUG=true
    depends_on:
      surrealdb:
        condition: service_healthy
    volumes:
      - .:/app
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  surrealdb_data: