version: '3.8'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - "23423:8000"
    command: start --log trace --user root --pass root memory
    volumes:
      - surrealdb_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  fastapi-app:
    build: .
    container_name: fastapi-auth-app
    ports:
      - "8001:8000"
    environment:
      - SURREALDB_URL=ws://surrealdb:8000/rpc
      - SURREALDB_NAMESPACE=test
      - SURREALDB_DATABASE=test
      - SURREALDB_USERNAME=root
      - SURREALDB_PASSWORD=root
      - SECRET_KEY=your-super-secret-key-change-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DEBUG=true
    depends_on:
      surrealdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  surrealdb_data:
    driver: local

networks:
  default:
    name: fastapi-surrealdb-network